# Generated by Django 6.0.6 on 2026-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperchunk',
            name='end_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperchunk',
            name='section_title',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='paperchunk',
            name='start_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
