# Generated by Django 6.0.6 on 2026-06-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paperchunk_end_line_paperchunk_section_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='General Academic Document', max_length=100)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('profile', models.TextField(blank=True, default='')),
                ('section_summaries', models.JSONField(blank=True, default=dict)),
                ('key_points', models.JSONField(blank=True, default=dict)),
                ('source_coverage', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='papers.paper')),
            ],
        ),
    ]
