# Generated by Django 6.0.6 on 2026-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_documentanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
