# Generated by Django 6.0.6 on 2026-06-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_chatmessage_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='OpenAlex', max_length=100)),
                ('openalex_id', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField(blank=True, default='')),
                ('authors', models.JSONField(blank=True, default=list)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.CharField(blank=True, default='', max_length=50)),
                ('venue', models.TextField(blank=True, default='')),
                ('doi', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.TextField(blank=True, default='')),
                ('pdf_url', models.TextField(blank=True, default='')),
                ('open_access', models.BooleanField(default=False)),
                ('open_access_status', models.CharField(blank=True, default='', max_length=100)),
                ('work_type', models.CharField(blank=True, default='', max_length=100)),
                ('cited_by_count', models.IntegerField(default=0)),
                ('abstract', models.TextField(blank=True, default='')),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('search_query', models.TextField(blank=True, default='')),
                ('why_related', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_papers', to='papers.paper')),
            ],
            options={
                'ordering': ['-cited_by_count', '-year'],
            },
        ),
    ]
